version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bringfood
    volumes:
      - db:/var/lib/mysql

  myadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      -  db

  web:
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    depends_on:
      -  php
    ports:
      - "3030:80"
volumes:
  db: