#version: '3.8'
#
#services:
#  db:
#    image: mariadb:latest
#    environment:
#     MARIADB_ROOT_PASSWORD: root
#
#  phpmyadmin:
#    image: phpmyadmin:latest
#    ports:
#      - "8080:80"
#    depends_on:
#      - db
#
#  php:
#    build:
#      context: .
#      dockerfile: Docker/php/Dockerfile
#    depends_on:
#      - db
#
#  nginx:
#    build:
#      context: .
#      dockerfile: Docker/nginx/Dockerfile
#    depends_on:
#      - php
#    ports:
#      - "3030:80"
version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      -  ./db:/var/lib/mysql

  myadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      -  db

  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    depends_on:
      -  db

  web:
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    depends_on:
      -  php
    ports:
      - "3030:80"